[env]
_.path = ['./node_modules/.bin']

[tools]

bun = 'latest'
deno = 'latest'
node = 'lts'
"npm:@google/gemini-cli" = "latest"

python = '3.14.3'

java = 'temurin-jre-25.0.2+10.0.LTS'

rust = { version = "latest" }
"cargo:tauri-cli" = 'latest'

fnox = "latest"

[plugins]

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
experimental = true
